### ISSUE TITLE
maybe a bug when adding noise

### ISSUE THREAD

**Issue by mrliudq** [dreasysnail/textCNN_public#4]
Hello,
Thanks for your generous code sharing.

While I want to add some noises to the sentences (in demo.py set opt.substitution='s' and opt.permutation=10), I find that the 'sents' and 'sents_permutated' are the same. Actually, the 'sents_permutated' had been permutated, but the same as 'sents'. they point to the same memory space.

You have used "sent_temp = sents[ss][:]" to make sure a list copy, but the 'sents' is a list of arrays, shallow copy doesn't work well. Maybe "import copy" and use deep copy such as "copy.deepcopy(sents)" could repair it.

**Comment by dreasysnail** [comment]
Hi mrliudq,

Thank you for pointing this out. We have checked the code, indeed it's a bug as what you found. The reason why we haven't identified it before is because if 'sents' is a list of list, it runs fine, which is typically the case in our tested dataset. So we add these two lines in the demo.py code, and this bug is solved.

    train = [list(s) for s in train]
    test = [list(s) for s in test]

I paste sample output as below.

Iteration 851000: loss 0.066530 
Original     :what is the best rewards credit card ?
Permutated   :cohm is the best recarxs crehit warh ?
Reconstructed:what is the best recards credit ware ?

**Comment by mrliudq** [comment]
Thanks~

**Comment by tuvuumass** [comment]
Should we remove  "test = [list(s) for s in test]"
I got the error
Traceback (most recent call last):
  File "textCNN_public-master/demo.py", line 315, in <module>
    main()
  File "textCNN_public-master/demo.py", line 193, in main
    test = [list(s) for s in test]
UnboundLocalError: local variable 'test' referenced before assignment
And the local variable 'test' is not used.
